# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: summerpen
subtitle: summerpen
description: 身体和灵魂,总有一个在路上
keywords: WEB
author: summerpen
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://summerpen.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
# highlight:
#   enable: false
#   line_number: true
#   auto_detect: false
#   tab_replace:

# 代码高亮
highlight:
  enable: false

prism_plugin:
  mode: "realtime" # realtime/preprocess
  theme: "tomorrow"
  line_number: false # default false
  custom_css:

#搜索
search:
  path: search.xml
  field: post
#  中文链接转拼音
permalink_pinyin:
  enable: true
  separator: "-" # default: '-'

# 文章字数统计插件(可选)
wordCount:
  enable: true # 将这个值设置为 true 即可.
  postWordCount: true
  min2read: true
  totalCount: true

# 添加 RSS 订阅支持（可选的）
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: " "
  order_by: -date

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery #使用主题 (theme文件夹下的主题)

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    coding: https://dev.tencent.com/u/summerpen/p/summerpen,master
    github: https://github.com/summerpen/summerpen.github.io,master

# deploy:    #阿里云虚拟主机,域名需要备案
#   type: ftpsync
#   host: byu6271070001.my3w.com  #主机地址
#   user: byu6271070001          #用户名
#   pass:           #密码
#   remote: /htdocs          #目录，应该所有阿里云虚拟主机的网站内容目录都是这个，不是根目录 /
#   port:
#   ignore: .DS_Store
#   connections:
#   verbose: true
